server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    <%_ if (sql == 'yes') { _%>
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:scripps;DB_CLOSE_DELAY=-1
        username: 
        password: 

    jpa:
        database-platform: <%=packageNameGenerated%>.domain.util.FixedH2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate.generate_statistics: true
    <%_ } _%>
    <%_ if (mongo == 'yes') { _%>
    data:
        mongodb:
            host: localhost
            port: 27017
            database: <%= baseName %>
    <%_ } _%>
    <%_ if (elastic == 'yes') { _%>
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
    <%_ } _%>

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: <%= baseName %>
